### ISSUE TITLE
Split freemarker templates into its own repo

### ISSUE THREAD

**Issue by testfile2** [SI-Gen/jportal2#56]
Split freemarker templates into its own repo (https://github.com/SI-Gen/jportal2-generator-templates)

**Comment by dieterrosch** [comment]
As part of this, we need to come up with a way to test the freemarker templates when a new version of jportal is released, as well as a way to show the freemarker sample output.

**Comment by ZoranPavlovic** [comment]
@dieterrosch - We discussed this previously. We semi-agreed on this being a "template" responsibility, if you recall? So ideally, the template repo's pipelines would test against whichever version of JPortal they're using, and include whichever tests it has.

**Comment by ZoranPavlovic** [comment]
On a side note... I think user testfile2 needs a bit of a name change. @dieterrosch ?

**Comment by dieterrosch** [comment]
> On a side note... I think user testfile2 needs a bit of a name change. @dieterrosch ?

Yup :)

**Comment by dieterrosch** [comment]
Done.
