### ISSUE TITLE
hook up the current azure devops pipeline to deploy to maven

### ISSUE THREAD

**Issue by testfile2** [SI-Gen/jportal2#58]

**Comment by ZoranPavlovic** [comment]
@testfile - Please chat to Gerardt as he's done some work for us regarding pushing this to Maven.

**Comment by testfile2** [comment]
> @testfile - Please chat to Gerardt as he's done some work for us regarding pushing this to Maven.

@ZoranPavlovic I believe he is briefed on the change. Just logged this for tracking

**Comment by dieterrosch** [comment]
Done.
